=== Grudzins/BMW_html/XML/bmw.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="bmw" type="bmwType"/>
	<xs:element name="link" type="mulType"/>
	<xs:element name="image" type="mulType"/>
	<xs:attribute name="czesc" type="czescType"/>

	<xs:group name="menuGroup">
		<xs:sequence>
			<xs:element name="menu1" type="krotszytekstType" minOccurs="0" maxOccurs="8"/>
			<xs:element name="menu2" type="krotszytekstType" minOccurs="0" maxOccurs="6"/>
		</xs:sequence>
	</xs:group>

	<xs:complexType name="bmwType">
		<xs:all>
			<xs:element name="menu" type="menuType"/>
			<xs:element name="glowna" type="glownaType"/>
			<xs:element name="M3" type="M3Type"/>
			<xs:element name="E30" type="E30Type"/>
			<xs:element name="E36" type="E36Type"/>
			<xs:element name="E46" type="E46Type"/>
			<xs:element name="E92" type="E92Type"/>
			<xs:element name="F80" type="F80Type"/>
			<xs:element name="G80" type="G80Type"/>
			<xs:element name="M5" type="M5Type"/>
			<xs:element name="E28" type="E28Type"/>
			<xs:element name="E34" type="E34Type"/>
			<xs:element name="E39" type="E39Type"/>
			<xs:element name="E60" type="E60Type"/>
			<xs:element name="F10" type="F10Type"/>
			<xs:element name="F90" type="F90Type"/>
			<xs:element name="M6" type="M6Type"/>
			<xs:element name="E24" type="E24Type"/>
			<xs:element name="E63" type="E63Type"/>
			<xs:element name="F13" type="F13Type"/>
			<xs:element name="galeria" type="galeriaType"/>
			<xs:element name="opinia" type="opiniaType"/>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="menuType">
		<xs:sequence>
			<xs:group ref="menuGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="glownaType">
		<xs:sequence>
			<xs:element name="opis" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="tekst" type="dluzszytekstType"/>
						<xs:element name="przesuwanie" type="krotszytekstType"/>
					</xs:sequence>
					<xs:attribute name="miejsce" type="miejsceType" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="M3Type">
			<xs:sequence>
				<xs:element name="opis">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tekst"/>
						</xs:sequence>
						<xs:attribute name="miejsce"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="wiersz" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="model">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="link">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="source" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="tyl">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="image">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="source" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="produkcja"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType >

	<xs:complexType name="M5Type">
			<xs:sequence>
				<xs:element name="opis">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tekst"/>
						</xs:sequence>
						<xs:attribute name="miejsce"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="wiersz" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="model">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="link">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="source" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="tyl">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="image">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="source" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="produkcja"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType >

	<xs:complexType name="M6Type">
			<xs:sequence>
				<xs:element name="opis">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tekst"/>
						</xs:sequence>
						<xs:attribute name="miejsce"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="wiersz" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="model">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="link">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="source" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="tyl">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="image">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="source" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="produkcja"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E30Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType >

	<xs:complexType name="E36Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType >

	<xs:complexType name="E46Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType >

	<xs:complexType name="E92Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType >

	<xs:complexType name="F80Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>
			

	<xs:complexType name="G80Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E28Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E34Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E39Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E60Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="F10Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="F90Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E24Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="E63Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="F13Type">
			<xs:sequence>
				<xs:element name="wstep"/>
				<xs:element name="image">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="source"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="dane"/>
				<xs:element name="przesuniecie"/>
			</xs:sequence>
			<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>

	<xs:complexType name="galeriaType">
		<xs:sequence>
			<xs:element name="image" maxOccurs="unbounded" minOccurs="0">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="opiniaType">
		<xs:sequence>
			<xs:element name="wstep"/>
			<xs:element name="dane">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="linie" type="fnType"/>
						<xs:element name="ocena" type="fnType"/>
						<xs:element name="powod" type="ftType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="czesc" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="mulType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="krotszytekstType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="29"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dluzszytekstType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="2000"/>
			<xs:minLength value="30"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="miejsceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gora"/>
			<xs:enumeration value="srodek"/>
			<xs:enumeration value="dol"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="czescType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="21"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ftType">
		<xs:list itemType="xs:string"/>
	</xs:simpleType>

	<xs:simpleType name="fnType">
	<xs:restriction base="listafn">
		<xs:maxLength value="5"/>
    </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="listafn">
		<xs:list itemType="xs:integer"/>
	</xs:simpleType>
</xs:schema>

=== Grudzins/BMW_html/XML/bmw.xml
<?xml version="1.0" encoding="utf-8"?>
<bmw xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="bmw.xsd">
	<menu>
		<menu1>
			Strona główna
			M3
		</menu1>
		<menu2>
			E30
			E36
			E46
			E92
			F80
			G80
		</menu2>
		<menu1>
			M5
		</menu1>
		<menu2>
			E28
			E34
			E39
			E60
			F10
			F90
		</menu2>
		<menu1>
			M6
		</menu1>
		<menu2>
			E24
			E63
			F13
		</menu2>
		<menu1>
			Galeria zdjęć
			Twoja opinia
		</menu1>
	</menu>
	<glowna czesc="1">
		<opis miejsce="gora">
			<tekst>
				Najwspanialsze dzieła BMW M Strona poświęcona najlepszym samochodom M Power w historii
			</tekst>
			<image source="img\header_logo_left.png"></image>
			<image source="img\header_logo_right.svg"></image>
		</opis>
		<opis miejsce ="srodek">
			<tekst>
				Witaj na stronie poświęconej najlepszym samochodom BMW M Power w historii,znajdziesz tutaj garść informacji na tematposzczególnych modeli oraz galerię zdjęć.Hipertekst i Hipermedia:Projekt I 2023 Temat: Moje hobby Wydział Elektroniki, Telekomunikacji i Informatyki Politechniki Gdańskiej
			</tekst>
		</opis>
		<opis miejsce="dol">
			<tekst>
				Autor: Jakub Grudziński
			</tekst>
		</opis>
	</glowna>
	<M3 czesc="2">
		<opis miejsce="gora">
			<tekst>
				BMW M3 - sportowa wersja samochodów BMW oparta na serii 3. Pierwsze BMW M3 pojawiło się w 1985 roku. Obecnie istnieje już 6 generacji tych pojazdów.
			</tekst>
		</opis>
		<wiersz>
			<model>
				<link source="https://pl.wikipedia.org/wiki/BMW_M3#BMW_M3_E30">BMW M3 E30</link>
			</model>
			<tyl>
				<image source="img\M3\Tył\E30.png"></image>
			</tyl>
			<produkcja>
				1986-1992
			</produkcja>
		</wiersz>
		<wiersz>
			<model>
				<link source="https://pl.wikipedia.org/wiki/BMW_M3#BMW_M3_E36">BMW M3 E36</link>
			</model>
			<tyl>
				<image source="img\M3\Tył\E36.png"></image>
			</tyl>
			<produkcja>
				1992-1999
			</produkcja>
		</wiersz>
		<wiersz>
			<model>
				<link source="https://pl.wikipedia.org/wiki/BMW_M3#BMW_M3_E46">BMW M3 E46</link>
			</model>
			<tyl>
				<image source="img\M3\Tył\E46.png"></image>
			</tyl>
			<produkcja>
				1999-2007
			</produkcja>
		</wiersz>
		<wiersz>
			<model>
				<link source="https://pl.wikipedia.org/wiki/BMW_M3#BMW_M3_E90/E92/E93">BMW M3 E92</link>
			</model>
			<tyl>
				<image source="img\M3\Tył\E92.png"></image>
			</tyl>
			<produkcja>
				2007-2013
			</produkcja>
		</wiersz>
		<wiersz>
			<model>
				<link source="https://pl.wikipedia.org/wiki/BMW_M3#BMW_M3_F80">BMW M3 F80</link>
			</model>
			<tyl>
				<image source="img\M3\Tył\F80.png"></image>
			</tyl>
			<produkcja>
				2013-2019
			</produkcja>
		</wiersz>
		<wiersz>
			<model>
				<link source="https://www.bmw.pl/pl/all-models/m-series/m3-sedan/2023/modele-bmw-serii-3-limuzyna-m-w-skrocie.html">BMW M3 G80</link>
			</model>
			<tyl>
				<image source="img\M3\Tył\G80.png"></image>
			</tyl>
			<produkcja>
				2021
			</produkcja>
		</wiersz>
	</M3>

	<E30 czesc="3">
		<wstep>
			BMW M3 E30 – pierwszy model M3. Oparty na BMW E30, produkowany był w dwóch wersjach nadwozia: coupé oraz kabriolet.
		</wstep>
		<image source="img\M3\BMW M3 E30.jpg"></image>
		<dane>
			Wyposażony był w czterocylindrowy silnik S14 o pojemności 2,3 bądź 2,5 litra i manualną skrzynię biegów. Wypuszczano też krótkie limitowane serie w celach m.in. homologacyjnych lub jako ukoronowanie zwycięstw w mistrzostwach DTM: M3 Evolution, M3 Evolution II, M3 Sport Evolution, M3 Europameister, M3 Roberto Ravaglia, M3 Johnny Cecotto, M3 Tour de Corse. M3 E30 Jest to model z największa liczbą zwycięstw w historii koncernu BMW oraz najbardziej utytułowane auto w klasie samochodów turystycznych. Jest jednym z najbardziej udanych samochodów sportowych, jakie kiedykolwiek startowały w wyścigach serii DTM.
		</dane>
		<przesuniecie>
			Powrót do góry
		</przesuniecie>
	</E30>

	<E36 czesc="4">
		<wstep>
			BMW M3 E36 – model oparty na BMW E36. Produkowany w wersji coupé, kabriolet oraz sedan. Wyposażony w sześciocylindrowy silnik S50 o pojemności 3.0 lub 3.2 litra oraz S52 w wersji amerykańskiej
		</wstep>
		<image source="img\M3\BMW M3 E36.jpg"></image>
		<dane>
			Model BMW M3 E36 był produkowany z przeznaczeniem na rynek europejski, amerykański oraz południowoafrykański. Na rynek amerykański M3 były oferowane z innymi silnikami niż na rynek europejski. BMW M3 US miało niezależnie od silnika (3.0 oraz 3.2) 240 KM, podczas gdy wersje europejskie w zależności od silnika miały 3.0 – 286 KM, 3.2 – 321 KM. Amerykańskie wersje M3 bazowały na silnikach M50/M52. Były o wiele bardziej podobne konstrukcyjnie do M50/M52 niż do prawdziwych silników z M3, a więc S53.
		</dane>
		<przesuniecie>
			Powrót do góry
		</przesuniecie>
	</E36>

	<E46 czesc="5">
		<wstep>
			BMW M3 E46 – model oparty na BMW E46. Produkowany w wersji coupé i kabriolet. Wyposażony w sześciocylindrowy silnik S54 o pojemności 3246 cm³.
		</wstep>
		<image source="img\M3\BMW M3 E46.jpg"></image>
		<dane>
			Model BMW M3 E46 był produkowany z przeznaczeniem na rynek europejski oraz amerykański. W początkowych modelach BMW M3 miały usterkę fabryczną polegającą na zastosowaniu wadliwego materiału przy produkcji panewek korbowodowych. Usterka ta często powodowała problemy silnikowe. BMW usuwało bezpłatnie usterkę, a w krytycznych przypadkach nawet wymieniało silnik. Warto zwrócić na powyższą przypadłość szczególną uwagę w egzemplarzach wyprodukowanych przed 2003 rokiem. Serwisy BMW na całym świecie wzywały właścicieli aut i nieodpłatnie wykonywały akcję serwisową polegająca na wymianie wadliwych panewek na właściwe.Samochód występuje w grach z serii Need for Speed: Most Wanted, kNeed for Speed: Payback, Need for Speed: Carbon i Need for Speed: World jako BMW M3 GTR.
		</dane>
		<przesuniecie>
			Powrót do góry
		</przesuniecie>
	</E46>

	<E92 czesc="6">
		<wstep>
			Model ten był produkowany od roku 2007.
		</wstep>
		<image source="img\M3\BMW M3 E92.jpg"></image>
		<dane>
			Ostatni egzemplarz M3 coupé opuścił fabrykę w lipcu 2013, natomiast zakończenie produkcji M3 Convertible miało miejsce we wrześniu 2013 roku. Jednocześnie niemiecki koncern podjął decyzję, że nie będzie kolejnej generacji M3 w wersji coupé oraz cabrio. Wersje te zostały zastąpione przez BMW M4 coupé oraz M4 cabrio.W samochodach BMW serii M3 E90/E92/E93 zastosowano nowy 4-litrowy silnik o zapłonie iskrowym V8 typ S65B40 osiągający moc 420 KM przy 8400 obr./min[5], w którym zainstalowano czujnik spalania stukowego w każdym cylindrze.BMW zaprezentowało „M3 GTS” w listopadzie 2009. Samochód napędzany jest 4,4-litrowym silnikiem V8 w oparciu o 4,0-litrowy silnik montowany standardowym M3, który osiąga maksymalnie 450 KM (331 kW). W sumie wyprodukowanych będzie tylko 99 sztuk. Dostawy w Niemczech zaczęły się od maja 2010. Ceny BMW E92 M3 GTS od € 115.000 za sztukę.Specjalne zawieszenie oraz unikatowy design nadwozia i wnętrza w czterech wariantach dostępnych tylko w krótkim okresie. Premiera na rynku odbyła się w lipcu 2009 roku, a sprzedaż zakończyła się w grudniu lub styczniu 2010 roku.Wersje M3 Edition, zbudowane w oparciu o BMW M3 Coupé, zastosowane zostały aluminiowe obręcze, a także obniżono zawieszenie o 10 milimetrów. Są dostępne w kolorach Alpine White, Black, Dakar Yellow oraz Monte Carlo Blue. Okres produkcji został ograniczony do zaledwie sześciu miesięcy, co pozwoliło zachować ekskluzywny charakter modeli. Model ten jest wyposażony tylko w skrzynie dwusprzęgłową DKG.BMW zaprezentowało nową, specjalną odmianę sportowej „M-trójki”. Model M3 Frozen Gray Edition zostanie zaoferowany w ograniczonym nakładzie 30 sztuk, a sprzedaż będzie odbywać się wyłącznie w USA. Z zewnątrz, nowy produkt BMW wyróżnia się niestandardowym lakierem karoserii, wewnątrz znajdziemy natomiast dwubarwną tapicerkę Fox Red and Black przygotowaną specjalnie dla tego modelu. Limitowane M3 otrzymało ponadto zestaw obniżający prześwit o 10 mm, nowe 19-calowe felgi, szersze ogumienie, a także system EDC odpowiadający za elektroniczną kontrolę amortyzacji.
		</dane>
		<przesuniecie>
			Powrót do góry
		</przesuniecie>
	</E92>

	<F80 czesc="7">
		<wstep>
			M3 F80 to pierwsze BMW M3 niedostępne w wersji coupé i cabrio, ich rolę przejęła seria 4 i model M4 (F82).
		</wstep>
		<image source="img\M3\BMW M3 F80.jpg"></image>
		<dane>
			W układzie przeniesienia napędu zastosowano sześciostopniową, ręczną skrzynię biegów oraz dwusprzęgłową przekładnię M DCT o siedmiu przełożeniach, Dzięki temu M3 rozpędza się do 100 km/h odpowiednio w 4,3 s oraz 4,1 s. Na życzenie klienta ogranicznik prędkości może zostać zdjęty. Wówczas samochody osiągnąć mogą prędkość maksymalną 270 km/h.
		</dane>
		<przesuniecie>
			Powrót do góry
		</przesuniecie>
	</F80>

	<G80 czesc="8">
		<wstep>
			Nowe BMW M3 G80 2021
		</wstep>
		<image source="img\M3\BMW M3 G80.jpg"></image>
		<dane>
